CREATE TABLE [dbo].[FlyerHistory] (
    [Id]                INT  IDENTITY (1, 1) NOT NULL,
    [ManagerName]       TEXT NOT NULL,
    [TemplateName]      TEXT NOT NULL,
    [StoreName]         TEXT NOT NULL,
    [StoreAddress]      TEXT NOT NULL,
    [StoreNumber]       TEXT NOT NULL,
    [FlyerCreationDate] TEXT NOT NULL,
    [FlyerStartDate]    TEXT NOT NULL,
	[FlyerEndDate]    TEXT NOT NULL,
    [SupplyChecked]     BIT  DEFAULT ((0)) NOT NULL,
    [RaincheckChecked]  BIT  DEFAULT ((0)) NOT NULL,
    [Item1Name]         TEXT NOT NULL,
    [Item1Price]        TEXT NOT NULL,
    [Item1Image]        TEXT NOT NULL,
    [Item1Size]         TEXT NOT NULL,
    [Item1Desc]         TEXT NULL,
    [Item2Name]         TEXT NULL,
    [Item2Price]        TEXT NULL,
    [Item2Image]        TEXT NULL,
    [Item2Size]         TEXT NULL,
    [Item2Desc]         TEXT NULL,
    [Item3Name]         TEXT NULL,
    [Item3Price]        TEXT NULL,
    [Item3Image]        TEXT NULL,
    [Item3Size]         TEXT NULL,
    [Item3Desc]         TEXT NULL,
    [Item4Name]         TEXT NULL,
    [Item4Price]        TEXT NULL,
    [Item4Image]        TEXT NULL,
    [Item4Size]         TEXT NULL,
    [Item4Desc]         TEXT NULL,
    [Item5Name]         TEXT NULL,
    [Item5Price]        TEXT NULL,
    [Item5Image]        TEXT NULL,
    [Item5Size]         TEXT NULL,
    [Item5Desc]         TEXT NULL,
    [Item6Name]         TEXT NULL,
    [Item6Price]        TEXT NULL,
    [Item6Image]        TEXT NULL,
    [Item6Size]         TEXT NULL,
    [Item6Desc]         TEXT NULL,
    [Item7Name]         TEXT NULL,
    [Item7Price]        TEXT NULL,
    [Item7Image]        TEXT NULL,
    [Item7Size]         TEXT NULL,
    [Item7Desc]         TEXT NULL,
    [Item8Name]         TEXT NULL,
    [Item8Price]        TEXT NULL,
    [Item8Image]        TEXT NULL,
    [Item8Size]         TEXT NULL,
    [Item8Desc]         TEXT NULL,
    [Item9Name]         TEXT NULL,
    [Item9Price]        TEXT NULL,
    [Item9Image]        TEXT NULL,
    [Item9Size]         TEXT NULL,
    [Item9Desc]         TEXT NULL,
    [Item10Name]        TEXT NULL,
    [Item10Price]       TEXT NULL,
    [Item10Image]       TEXT NULL,
    [Item10Size]        TEXT NULL,
    [Item10Desc]        TEXT NULL,
    [Item11Name]        TEXT NULL,
    [Item11Price]       TEXT NULL,
    [Item11Image]       TEXT NULL,
    [Item11Size]        TEXT NULL,
    [Item11Desc]        TEXT NULL,
    [Item12Name]        TEXT NULL,
    [Item12Price]       TEXT NULL,
    [Item12Image]       TEXT NULL,
    [Item12Size]        TEXT NULL,
    [Item12Desc]        TEXT NULL,
    [Item13Name]        TEXT NULL,
    [Item13Price]       TEXT NULL,
    [Item13Image]       TEXT NULL,
    [Item13Size]        TEXT NULL,
    [Item13Desc]        TEXT NULL,
    [Item14Name]        TEXT NULL,
    [Item14Price]       TEXT NULL,
    [Item14Image]       TEXT NULL,
    [Item14Size]        TEXT NULL,
    [Item14Desc]        TEXT NULL,
    [Item15Name]        TEXT NULL,
    [Item15Price]       TEXT NULL,
    [Item15Image]       TEXT NULL,
    [Item15Size]        TEXT NULL,
    [Item15Desc]        TEXT NULL,
    [Item16Name]        TEXT NULL,
    [Item16Price]       TEXT NULL,
    [Item16Image]       TEXT NULL,
    [Item16Size]        TEXT NULL,
    [Item16Desc]        TEXT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

